apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: merit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app-image
          image: merit237/spring-boot-app:v${BUILD_NUMBER}
